.TH "AddrSpace" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddrSpace \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddrSpace\fP (\fBOpenFile\fP *executable)"
.br
.ti -1c
.RI "void \fBInitRegisters\fP ()"
.br
.ti -1c
.RI "void \fBSaveState\fP ()"
.br
.ti -1c
.RI "void \fBRestoreState\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file addrspace\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
