.TH "aouthdr" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aouthdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBmagic\fP"
.br
.ti -1c
.RI "short \fBvstamp\fP"
.br
.ti -1c
.RI "long \fBtsize\fP"
.br
.ti -1c
.RI "long \fBdsize\fP"
.br
.ti -1c
.RI "long \fBbsize\fP"
.br
.ti -1c
.RI "long \fBentry\fP"
.br
.ti -1c
.RI "long \fBtext_start\fP"
.br
.ti -1c
.RI "long \fBdata_start\fP"
.br
.ti -1c
.RI "long \fBbss_start\fP"
.br
.ti -1c
.RI "long \fBgprmask\fP"
.br
.ti -1c
.RI "long \fBcprmask\fP [4]"
.br
.ti -1c
.RI "long \fBgp_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file coff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
