.TH "code/userprog/bitmap.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/userprog/bitmap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br
\fC#include 'openfile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBitMap\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBitsInByte\fP   8"
.br
.ti -1c
.RI "#define \fBBitsInWord\fP   32"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BitsInByte   8"

.PP
Definition at line 23 of file bitmap\&.h\&.
.SS "#define BitsInWord   32"

.PP
Definition at line 24 of file bitmap\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
