.TH "BitMap" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitMap \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitMap\fP (int nitems)"
.br
.ti -1c
.RI "void \fBMark\fP (int which)"
.br
.ti -1c
.RI "void \fBClear\fP (int which)"
.br
.ti -1c
.RI "bool \fBTest\fP (int which)"
.br
.ti -1c
.RI "int \fBFind\fP ()"
.br
.ti -1c
.RI "int \fBNumClear\fP ()"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.ti -1c
.RI "void \fBFetchFrom\fP (\fBOpenFile\fP *file)"
.br
.ti -1c
.RI "void \fBWriteBack\fP (\fBOpenFile\fP *file)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file bitmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
