.TH "code/threads/bool.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/threads/bool.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRUE\fP   \fBtrue\fP"
.br
.ti -1c
.RI "#define \fBFALSE\fP   \fBfalse\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   \fBfalse\fP"

.PP
Definition at line 13 of file bool\&.h\&.
.SS "#define TRUE   \fBtrue\fP"

.PP
Definition at line 12 of file bool\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
