.TH "code/bin/coff.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/coff.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfilehdr\fP"
.br
.ti -1c
.RI "struct \fBaouthdr\fP"
.br
.ti -1c
.RI "struct \fBscnhdr\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIPSELMAGIC\fP   0x0162"
.br
.ti -1c
.RI "#define \fBOMAGIC\fP   0407"
.br
.ti -1c
.RI "#define \fBSOMAGIC\fP   0x0701"
.br
.ti -1c
.RI "#define \fBAOUTHSZ\fP   sizeof(\fBAOUTHDR\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBaouthdr\fP \fBAOUTHDR\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AOUTHSZ   sizeof(\fBAOUTHDR\fP)"

.PP
Definition at line 34 of file coff\&.h\&.
.SS "#define MIPSELMAGIC   0x0162"

.PP
Definition at line 15 of file coff\&.h\&.
.SS "#define OMAGIC   0407"

.PP
Definition at line 17 of file coff\&.h\&.
.SS "#define SOMAGIC   0x0701"

.PP
Definition at line 18 of file coff\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBaouthdr\fP  \fBAOUTHDR\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
