.TH "Condition" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Condition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondition\fP (const char *debugName)"
.br
.ti -1c
.RI "const char * \fBgetName\fP () const "
.br
.ti -1c
.RI "void \fBWait\fP (\fBLock\fP *conditionLock)"
.br
.ti -1c
.RI "void \fBSignal\fP (\fBLock\fP *conditionLock)"
.br
.ti -1c
.RI "void \fBBroadcast\fP (\fBLock\fP *conditionLock)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file synch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
