.TH "Console" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSynchConsole\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsole\fP (char *readFile, char *writeFile, VoidFunctionPtr readAvail, VoidFunctionPtr writeDone, int callArg)"
.br
.ti -1c
.RI "virtual void \fBPutChar\fP (char ch)"
.br
.ti -1c
.RI "virtual int \fBGetChar\fP ()"
.br
.ti -1c
.RI "void \fBWriteDone\fP ()"
.br
.ti -1c
.RI "void \fBCheckCharAvail\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file console\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
