.TH "data" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBdata\fP [MAXDATA]"
.br
.ti -1c
.RI "struct reloc \fBreloc\fP [MAXRELOCS]"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBrelocs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file out\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
