.TH "code/filesys/directory.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/filesys/directory.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br
\fC#include 'filehdr\&.h'\fP
.br
\fC#include 'directory\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
