.TH "code/filesys/directory.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/filesys/directory.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'openfile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectoryEntry\fP"
.br
.ti -1c
.RI "class \fBDirectory\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFileNameMaxLen\fP   9"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FileNameMaxLen   9"

.PP
Definition at line 22 of file directory\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
