.TH "code/bin/disasm.c" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/disasm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <filehdr\&.h>\fP
.br
\fC#include <scnhdr\&.h>\fP
.br
\fC#include <syms\&.h>\fP
.br
\fC#include <ldfcn\&.h>\fP
.br
\fC#include 'int\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOADSECTION\fP(head)   \fBload_section\fP(&head);"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBstrcpy\fP ()"
.br
.ti -1c
.RI "\fBmain\fP (int argc, argv)"
.br
.ti -1c
.RI "\fBload_section\fP (SCNHDR *hd)"
.br
.ti -1c
.RI "\fBload_program\fP (char *filename)"
.br
.ti -1c
.RI "int * \fBm_alloc\fP (int n)"
.br
.ti -1c
.RI "\fBdisasm\fP (int startpc, int argc, argv)"
.br
.ti -1c
.RI "\fBdis1\fP (int xpc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBmem\fP [\fBMEMSIZE\fP]"
.br
.ti -1c
.RI "int \fBTRACE\fP"
.br
.ti -1c
.RI "int \fBTraptrace\fP"
.br
.ti -1c
.RI "int \fBRegtrace\fP"
.br
.ti -1c
.RI "int \fBNROWS\fP =64"
.br
.ti -1c
.RI "int \fBASSOC\fP =1"
.br
.ti -1c
.RI "int \fBLINESIZE\fP =4"
.br
.ti -1c
.RI "int \fBRAND\fP =0"
.br
.ti -1c
.RI "int \fBLRD\fP =0"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOADSECTION(head)   \fBload_section\fP(&head);"

.PP
Definition at line 69 of file disasm\&.c\&.
.SH "Function Documentation"
.PP 
.SS "dis1 (int xpc)"

.PP
Definition at line 162 of file disasm\&.c\&.
.SS "disasm (int startpc, int argc, argv)"

.PP
Definition at line 148 of file disasm\&.c\&.
.SS "load_program (char * filename)"

.PP
Definition at line 88 of file disasm\&.c\&.
.SS "load_section (SCNHDR * hd)"

.PP
Definition at line 71 of file disasm\&.c\&.
.SS "int* m_alloc (int n)"

.PP
Definition at line 140 of file disasm\&.c\&.
.SS "main (int argc, argv)"

.PP
Definition at line 32 of file disasm\&.c\&.
.SS "char* strcpy ()"

.SH "Variable Documentation"
.PP 
.SS "int ASSOC =1"

.PP
Definition at line 27 of file disasm\&.c\&.
.SS "int LINESIZE =4"

.PP
Definition at line 27 of file disasm\&.c\&.
.SS "int LRD =0"

.PP
Definition at line 27 of file disasm\&.c\&.
.SS "char mem[\fBMEMSIZE\fP]"

.PP
Definition at line 25 of file disasm\&.c\&.
.SS "int NROWS =64"

.PP
Definition at line 27 of file disasm\&.c\&.
.SS "int pc"

.PP
Definition at line 28 of file disasm\&.c\&.
.SS "int RAND =0"

.PP
Definition at line 27 of file disasm\&.c\&.
.SS "int Regtrace"

.PP
Definition at line 26 of file disasm\&.c\&.
.SS "int TRACE"

.PP
Definition at line 26 of file disasm\&.c\&.
.SS "int Traptrace"

.PP
Definition at line 26 of file disasm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
