.TH "code/machine/disk.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/disk.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDisk\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSectorSize\fP   128"
.br
.ti -1c
.RI "#define \fBSectorsPerTrack\fP   32"
.br
.ti -1c
.RI "#define \fBNumTracks\fP   32"
.br
.ti -1c
.RI "#define \fBNumSectors\fP   (\fBSectorsPerTrack\fP * \fBNumTracks\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NumSectors   (\fBSectorsPerTrack\fP * \fBNumTracks\fP)"

.PP
Definition at line 52 of file disk\&.h\&.
.SS "#define NumTracks   32"

.PP
Definition at line 51 of file disk\&.h\&.
.SS "#define SectorSize   128"

.PP
Definition at line 49 of file disk\&.h\&.
.SS "#define SectorsPerTrack   32"

.PP
Definition at line 50 of file disk\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
