.TH "code/machine/disk.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/disk.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'disk\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMagicNumber\fP   0x456789ab"
.br
.ti -1c
.RI "#define \fBMagicSize\fP   sizeof(int)"
.br
.ti -1c
.RI "#define \fBDiskSize\fP   (\fBMagicSize\fP + (\fBNumSectors\fP * \fBSectorSize\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DiskSize   (\fBMagicSize\fP + (\fBNumSectors\fP * \fBSectorSize\fP))"

.PP
Definition at line 26 of file disk\&.cc\&.
.SS "#define MagicNumber   0x456789ab"

.PP
Definition at line 23 of file disk\&.cc\&.
.SS "#define MagicSize   sizeof(int)"

.PP
Definition at line 24 of file disk\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
