.TH "code/bin/encode.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/encode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI_SPECIAL\fP   000"
.br
.ti -1c
.RI "#define \fBI_BCOND\fP   001"
.br
.ti -1c
.RI "#define \fBI_J\fP   002"
.br
.ti -1c
.RI "#define \fBI_JAL\fP   003"
.br
.ti -1c
.RI "#define \fBI_BEQ\fP   004"
.br
.ti -1c
.RI "#define \fBI_BNE\fP   005"
.br
.ti -1c
.RI "#define \fBI_BLEZ\fP   006"
.br
.ti -1c
.RI "#define \fBI_BGTZ\fP   007"
.br
.ti -1c
.RI "#define \fBI_ADDI\fP   010"
.br
.ti -1c
.RI "#define \fBI_ADDIU\fP   011"
.br
.ti -1c
.RI "#define \fBI_SLTI\fP   012"
.br
.ti -1c
.RI "#define \fBI_SLTIU\fP   013"
.br
.ti -1c
.RI "#define \fBI_ANDI\fP   014"
.br
.ti -1c
.RI "#define \fBI_ORI\fP   015"
.br
.ti -1c
.RI "#define \fBI_XORI\fP   016"
.br
.ti -1c
.RI "#define \fBI_LUI\fP   017"
.br
.ti -1c
.RI "#define \fBI_COP0\fP   020"
.br
.ti -1c
.RI "#define \fBI_COP1\fP   021"
.br
.ti -1c
.RI "#define \fBI_COP2\fP   022"
.br
.ti -1c
.RI "#define \fBI_COP3\fP   023"
.br
.ti -1c
.RI "#define \fBI_LB\fP   040"
.br
.ti -1c
.RI "#define \fBI_LH\fP   041"
.br
.ti -1c
.RI "#define \fBI_LWL\fP   042"
.br
.ti -1c
.RI "#define \fBI_LW\fP   043"
.br
.ti -1c
.RI "#define \fBI_LBU\fP   044"
.br
.ti -1c
.RI "#define \fBI_LHU\fP   045"
.br
.ti -1c
.RI "#define \fBI_LWR\fP   046"
.br
.ti -1c
.RI "#define \fBI_SB\fP   050"
.br
.ti -1c
.RI "#define \fBI_SH\fP   051"
.br
.ti -1c
.RI "#define \fBI_SWL\fP   052"
.br
.ti -1c
.RI "#define \fBI_SW\fP   053"
.br
.ti -1c
.RI "#define \fBI_SWR\fP   056"
.br
.ti -1c
.RI "#define \fBI_LWC0\fP   060"
.br
.ti -1c
.RI "#define \fBI_LWC1\fP   061"
.br
.ti -1c
.RI "#define \fBI_LWC2\fP   062"
.br
.ti -1c
.RI "#define \fBI_LWC3\fP   063"
.br
.ti -1c
.RI "#define \fBI_SWC0\fP   070"
.br
.ti -1c
.RI "#define \fBI_SWC1\fP   071"
.br
.ti -1c
.RI "#define \fBI_SWC2\fP   072"
.br
.ti -1c
.RI "#define \fBI_SWC3\fP   073"
.br
.ti -1c
.RI "#define \fBI_SLL\fP   000"
.br
.ti -1c
.RI "#define \fBI_SRL\fP   002"
.br
.ti -1c
.RI "#define \fBI_SRA\fP   003"
.br
.ti -1c
.RI "#define \fBI_SLLV\fP   004"
.br
.ti -1c
.RI "#define \fBI_SRLV\fP   006"
.br
.ti -1c
.RI "#define \fBI_SRAV\fP   007"
.br
.ti -1c
.RI "#define \fBI_JR\fP   010"
.br
.ti -1c
.RI "#define \fBI_JALR\fP   011"
.br
.ti -1c
.RI "#define \fBI_SYSCALL\fP   014"
.br
.ti -1c
.RI "#define \fBI_BREAK\fP   015"
.br
.ti -1c
.RI "#define \fBI_MFHI\fP   020"
.br
.ti -1c
.RI "#define \fBI_MTHI\fP   021"
.br
.ti -1c
.RI "#define \fBI_MFLO\fP   022"
.br
.ti -1c
.RI "#define \fBI_MTLO\fP   023"
.br
.ti -1c
.RI "#define \fBI_MULT\fP   030"
.br
.ti -1c
.RI "#define \fBI_MULTU\fP   031"
.br
.ti -1c
.RI "#define \fBI_DIV\fP   032"
.br
.ti -1c
.RI "#define \fBI_DIVU\fP   033"
.br
.ti -1c
.RI "#define \fBI_ADD\fP   040"
.br
.ti -1c
.RI "#define \fBI_ADDU\fP   041"
.br
.ti -1c
.RI "#define \fBI_SUB\fP   042"
.br
.ti -1c
.RI "#define \fBI_SUBU\fP   043"
.br
.ti -1c
.RI "#define \fBI_AND\fP   044"
.br
.ti -1c
.RI "#define \fBI_OR\fP   045"
.br
.ti -1c
.RI "#define \fBI_XOR\fP   046"
.br
.ti -1c
.RI "#define \fBI_NOR\fP   047"
.br
.ti -1c
.RI "#define \fBI_SLT\fP   052"
.br
.ti -1c
.RI "#define \fBI_SLTU\fP   053"
.br
.ti -1c
.RI "#define \fBI_BLTZ\fP   000"
.br
.ti -1c
.RI "#define \fBI_BGEZ\fP   001"
.br
.ti -1c
.RI "#define \fBI_BLTZAL\fP   020"
.br
.ti -1c
.RI "#define \fBI_BGEZAL\fP   021"
.br
.ti -1c
.RI "#define \fBI_NOP\fP   000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define I_ADD   040"

.PP
Definition at line 84 of file encode\&.h\&.
.SS "#define I_ADDI   010"

.PP
Definition at line 20 of file encode\&.h\&.
.SS "#define I_ADDIU   011"

.PP
Definition at line 21 of file encode\&.h\&.
.SS "#define I_ADDU   041"

.PP
Definition at line 85 of file encode\&.h\&.
.SS "#define I_AND   044"

.PP
Definition at line 88 of file encode\&.h\&.
.SS "#define I_ANDI   014"

.PP
Definition at line 24 of file encode\&.h\&.
.SS "#define I_BCOND   001"

.PP
Definition at line 13 of file encode\&.h\&.
.SS "#define I_BEQ   004"

.PP
Definition at line 16 of file encode\&.h\&.
.SS "#define I_BGEZ   001"

.PP
Definition at line 100 of file encode\&.h\&.
.SS "#define I_BGEZAL   021"

.PP
Definition at line 103 of file encode\&.h\&.
.SS "#define I_BGTZ   007"

.PP
Definition at line 19 of file encode\&.h\&.
.SS "#define I_BLEZ   006"

.PP
Definition at line 18 of file encode\&.h\&.
.SS "#define I_BLTZ   000"

.PP
Definition at line 99 of file encode\&.h\&.
.SS "#define I_BLTZAL   020"

.PP
Definition at line 102 of file encode\&.h\&.
.SS "#define I_BNE   005"

.PP
Definition at line 17 of file encode\&.h\&.
.SS "#define I_BREAK   015"

.PP
Definition at line 72 of file encode\&.h\&.
.SS "#define I_COP0   020"

.PP
Definition at line 28 of file encode\&.h\&.
.SS "#define I_COP1   021"

.PP
Definition at line 29 of file encode\&.h\&.
.SS "#define I_COP2   022"

.PP
Definition at line 30 of file encode\&.h\&.
.SS "#define I_COP3   023"

.PP
Definition at line 31 of file encode\&.h\&.
.SS "#define I_DIV   032"

.PP
Definition at line 81 of file encode\&.h\&.
.SS "#define I_DIVU   033"

.PP
Definition at line 82 of file encode\&.h\&.
.SS "#define I_J   002"

.PP
Definition at line 14 of file encode\&.h\&.
.SS "#define I_JAL   003"

.PP
Definition at line 15 of file encode\&.h\&.
.SS "#define I_JALR   011"

.PP
Definition at line 69 of file encode\&.h\&.
.SS "#define I_JR   010"

.PP
Definition at line 68 of file encode\&.h\&.
.SS "#define I_LB   040"

.PP
Definition at line 33 of file encode\&.h\&.
.SS "#define I_LBU   044"

.PP
Definition at line 37 of file encode\&.h\&.
.SS "#define I_LH   041"

.PP
Definition at line 34 of file encode\&.h\&.
.SS "#define I_LHU   045"

.PP
Definition at line 38 of file encode\&.h\&.
.SS "#define I_LUI   017"

.PP
Definition at line 27 of file encode\&.h\&.
.SS "#define I_LW   043"

.PP
Definition at line 36 of file encode\&.h\&.
.SS "#define I_LWC0   060"

.PP
Definition at line 48 of file encode\&.h\&.
.SS "#define I_LWC1   061"

.PP
Definition at line 49 of file encode\&.h\&.
.SS "#define I_LWC2   062"

.PP
Definition at line 50 of file encode\&.h\&.
.SS "#define I_LWC3   063"

.PP
Definition at line 51 of file encode\&.h\&.
.SS "#define I_LWL   042"

.PP
Definition at line 35 of file encode\&.h\&.
.SS "#define I_LWR   046"

.PP
Definition at line 39 of file encode\&.h\&.
.SS "#define I_MFHI   020"

.PP
Definition at line 74 of file encode\&.h\&.
.SS "#define I_MFLO   022"

.PP
Definition at line 76 of file encode\&.h\&.
.SS "#define I_MTHI   021"

.PP
Definition at line 75 of file encode\&.h\&.
.SS "#define I_MTLO   023"

.PP
Definition at line 77 of file encode\&.h\&.
.SS "#define I_MULT   030"

.PP
Definition at line 79 of file encode\&.h\&.
.SS "#define I_MULTU   031"

.PP
Definition at line 80 of file encode\&.h\&.
.SS "#define I_NOP   000"

.PP
Definition at line 107 of file encode\&.h\&.
.SS "#define I_NOR   047"

.PP
Definition at line 91 of file encode\&.h\&.
.SS "#define I_OR   045"

.PP
Definition at line 89 of file encode\&.h\&.
.SS "#define I_ORI   015"

.PP
Definition at line 25 of file encode\&.h\&.
.SS "#define I_SB   050"

.PP
Definition at line 41 of file encode\&.h\&.
.SS "#define I_SH   051"

.PP
Definition at line 42 of file encode\&.h\&.
.SS "#define I_SLL   000"

.PP
Definition at line 60 of file encode\&.h\&.
.SS "#define I_SLLV   004"

.PP
Definition at line 64 of file encode\&.h\&.
.SS "#define I_SLT   052"

.PP
Definition at line 93 of file encode\&.h\&.
.SS "#define I_SLTI   012"

.PP
Definition at line 22 of file encode\&.h\&.
.SS "#define I_SLTIU   013"

.PP
Definition at line 23 of file encode\&.h\&.
.SS "#define I_SLTU   053"

.PP
Definition at line 94 of file encode\&.h\&.
.SS "#define I_SPECIAL   000"

.PP
Definition at line 12 of file encode\&.h\&.
.SS "#define I_SRA   003"

.PP
Definition at line 63 of file encode\&.h\&.
.SS "#define I_SRAV   007"

.PP
Definition at line 67 of file encode\&.h\&.
.SS "#define I_SRL   002"

.PP
Definition at line 62 of file encode\&.h\&.
.SS "#define I_SRLV   006"

.PP
Definition at line 66 of file encode\&.h\&.
.SS "#define I_SUB   042"

.PP
Definition at line 86 of file encode\&.h\&.
.SS "#define I_SUBU   043"

.PP
Definition at line 87 of file encode\&.h\&.
.SS "#define I_SW   053"

.PP
Definition at line 44 of file encode\&.h\&.
.SS "#define I_SWC0   070"

.PP
Definition at line 53 of file encode\&.h\&.
.SS "#define I_SWC1   071"

.PP
Definition at line 54 of file encode\&.h\&.
.SS "#define I_SWC2   072"

.PP
Definition at line 55 of file encode\&.h\&.
.SS "#define I_SWC3   073"

.PP
Definition at line 56 of file encode\&.h\&.
.SS "#define I_SWL   052"

.PP
Definition at line 43 of file encode\&.h\&.
.SS "#define I_SWR   056"

.PP
Definition at line 46 of file encode\&.h\&.
.SS "#define I_SYSCALL   014"

.PP
Definition at line 71 of file encode\&.h\&.
.SS "#define I_XOR   046"

.PP
Definition at line 90 of file encode\&.h\&.
.SS "#define I_XORI   016"

.PP
Definition at line 26 of file encode\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
