.TH "code/bin/execute.c" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/execute.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'instr\&.h'\fP
.br
\fC#include 'encode\&.h'\fP
.br
\fC#include 'int\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFAST\fP   0"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBb31\fP(z)   (((z) >>31 )&0x1)	/* extract bit 31 */"
.br
.ti -1c
.RI "#define \fBcc_add\fP(rr,  op1,  op2)"
.br
.ti -1c
.RI "#define \fBcc_sub\fP(rr,  op1,  op2)"
.br
.ti -1c
.RI "#define \fBcc_logic\fP(rr)"
.br
.ti -1c
.RI "#define \fBcc_mulscc\fP(rr,  op1,  op2)"
.br
.ti -1c
.RI "#define \fBNH\fP   32"
.br
.ti -1c
.RI "#define \fBNNN\fP   33"
.br
.ti -1c
.RI "#define \fBNNNN\fP   (64)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrunprogram\fP (int startpc, int argc, argv)"
.br
.ti -1c
.RI "\fBu\fP ()"
.br
.ti -1c
.RI "\fBny\fP ()"
.br
.ti -1c
.RI "\fBdump_reg\fP ()"
.br
.ti -1c
.RI "\fBilog2\fP (int \fBi\fP)"
.br
.ti -1c
.RI "void \fBhenters\fP (int n, int hist)"
.br
.ti -1c
.RI "\fBhprint\fP ()"
.br
.ti -1c
.RI "\fBpatable\fP (tab)"
.br
.ti -1c
.RI "\fBprintstatistics\fP ()"
.br
.ti -1c
.RI "\fBhenter\fP (int n)"
.br
.ti -1c
.RI "\fBprinthist\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBmem\fP []"
.br
.ti -1c
.RI "int \fBTRACE\fP"
.br
.ti -1c
.RI "int \fBRegtrace\fP"
.br
.ti -1c
.RI "int \fBReg\fP [32]"
.br
.ti -1c
.RI "int \fBHI\fP"
.br
.ti -1c
.RI "int \fBLO\fP"
.br
.ti -1c
.RI "int \fBnumjmpls\fP"
.br
.ti -1c
.RI "int \fBarch1cycles\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBhoflo\fP [\fBNH\fP]"
.br
.ti -1c
.RI "int \fBhtotal\fP [\fBNH\fP]"
.br
.ti -1c
.RI "int \fBnumadds\fP =1"
.br
.ti -1c
.RI "int \fBnumsubs\fP =1"
.br
.ti -1c
.RI "int \fBnumsuccesses\fP"
.br
.ti -1c
.RI "int \fBnumcarries\fP"
.br
.ti -1c
.RI "int \fBaddtable\fP [33][33]"
.br
.ti -1c
.RI "int \fBsubtable\fP [33][33]"
.br
.ti -1c
.RI "char \fBfmt\fP [] = '%6d'"
.br
.ti -1c
.RI "char \fBfmt2\fP [] = '\-\-\-\-\-\-'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define b31(z)   (((z) >>31 )&0x1)	/* extract bit 31 */"

.PP
Definition at line 31 of file execute\&.c\&.
.SS "#define cc_add(rr, op1, op2)"
\fBValue:\fP
.PP
.nf
N = (rr < 0);    \
    Z = (rr == 0);  \\
	C = ((unsigned) rr < (unsigned) op2);  \
    V = ((op1^op2) >= 0  &&  (op1^rr) < 0);
.fi
.PP
Definition at line 34 of file execute\&.c\&.
.SS "#define cc_logic(rr)"
\fBValue:\fP
.PP
.nf
N = (rr < 0); \
    Z = (rr == 0);  \
    V = 0;  \\
	C = 0;
.fi
.PP
Definition at line 48 of file execute\&.c\&.
.SS "#define cc_mulscc(rr, op1, op2)"
\fBValue:\fP
.PP
.nf
N = (rr < 0);  \
    Z = (rr == 0);  \
    V = b31((op1 & op2 & ~rr) | (~op1 & ~op2 & rr));    \\
	C = b31((op1 & op2) | (~rr & (op1 | op2)));
.fi
.PP
Definition at line 54 of file execute\&.c\&.
.SS "#define cc_sub(rr, op1, op2)"
\fBValue:\fP
.PP
.nf
N = (rr < 0); \
    Z = (rr == 0);  \
    V = b31((op1 & ~op2 & ~rr) | (~op1 & op2 & rr));    \\
	C = ((unsigned) op1 < (unsigned) op2);
.fi
.PP
Definition at line 40 of file execute\&.c\&.
.SS "#define false   0"

.PP
Definition at line 16 of file execute\&.c\&.
.SS "#define FAST   0"

.PP
Definition at line 14 of file execute\&.c\&.
.SS "#define NH   32"

.PP
Definition at line 465 of file execute\&.c\&.
.SS "#define NNN   33"

.PP
Definition at line 466 of file execute\&.c\&.
.SS "#define NNNN   (64)"

.PP
Definition at line 555 of file execute\&.c\&.
.SS "#define true   1"

.PP
Definition at line 15 of file execute\&.c\&.
.SH "Function Documentation"
.PP 
.SS "dump_reg ()"

.PP
Definition at line 417 of file execute\&.c\&.
.SS "henter (int n)"

.PP
Definition at line 559 of file execute\&.c\&.
.SS "void henters (int n, int hist)"

.PP
Definition at line 471 of file execute\&.c\&.
.SS "hprint ()"

.PP
Definition at line 478 of file execute\&.c\&.
.SS "ilog2 (int i)"

.PP
Definition at line 447 of file execute\&.c\&.
.SS "ny ()"

.PP
Definition at line 383 of file execute\&.c\&.
.SS "patable (tab)"

.PP
Definition at line 508 of file execute\&.c\&.
.SS "printhist ()"

.PP
Definition at line 566 of file execute\&.c\&.
.SS "printstatistics ()"

.PP
Definition at line 533 of file execute\&.c\&.
.SS "runprogram (int startpc, int argc, argv)"

.PP
Definition at line 61 of file execute\&.c\&.
.SS "u ()"

.PP
Definition at line 378 of file execute\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int addtable[33][33]"

.PP
Definition at line 502 of file execute\&.c\&.
.SS "int arch1cycles"

.PP
Definition at line 28 of file execute\&.c\&.
.SS "char fmt[] = '%6d'"

.PP
Definition at line 505 of file execute\&.c\&.
.SS "char fmt2[] = '\-\-\-\-\-\-'"

.PP
Definition at line 506 of file execute\&.c\&.
.SS "int HI"

.PP
Definition at line 24 of file execute\&.c\&.
.SS "int hoflo[\fBNH\fP]"

.PP
Definition at line 469 of file execute\&.c\&.
.SS "int htotal[\fBNH\fP]"

.PP
Definition at line 469 of file execute\&.c\&.
.SS "int i"
\fBInitial value:\fP
.PP
.nf
{
    return rs(i)
.fi
.PP
Definition at line 392 of file execute\&.c\&.
.SS "int LO"

.PP
Definition at line 24 of file execute\&.c\&.
.SS "char mem[]"

.PP
Definition at line 25 of file disasm\&.c\&.
.SS "int numadds =1"

.PP
Definition at line 501 of file execute\&.c\&.
.SS "int numcarries"

.PP
Definition at line 501 of file execute\&.c\&.
.SS "int numjmpls"

.PP
Definition at line 27 of file execute\&.c\&.
.SS "int numsubs =1"

.PP
Definition at line 501 of file execute\&.c\&.
.SS "int numsuccesses"

.PP
Definition at line 501 of file execute\&.c\&.
.SS "int Reg[32]"

.PP
Definition at line 23 of file execute\&.c\&.
.SS "int Regtrace"

.PP
Definition at line 26 of file disasm\&.c\&.
.SS "int subtable[33][33]"

.PP
Definition at line 503 of file execute\&.c\&.
.SS "int TRACE"

.PP
Definition at line 26 of file disasm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
