.TH "code/filesys/filehdr.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/filesys/filehdr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'disk\&.h'\fP
.br
\fC#include 'bitmap\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileHeader\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNumDirect\fP   ((\fBSectorSize\fP \- 2 * sizeof(int)) / sizeof(int))"
.br
.ti -1c
.RI "#define \fBMaxFileSize\fP   (\fBNumDirect\fP * \fBSectorSize\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MaxFileSize   (\fBNumDirect\fP * \fBSectorSize\fP)"

.PP
Definition at line 21 of file filehdr\&.h\&.
.SS "#define NumDirect   ((\fBSectorSize\fP \- 2 * sizeof(int)) / sizeof(int))"

.PP
Definition at line 20 of file filehdr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
