.TH "FileHeader" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileHeader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBAllocate\fP (\fBBitMap\fP *bitMap, int fileSize)"
.br
.ti -1c
.RI "void \fBDeallocate\fP (\fBBitMap\fP *bitMap)"
.br
.ti -1c
.RI "void \fBFetchFrom\fP (int sectorNumber)"
.br
.ti -1c
.RI "void \fBWriteBack\fP (int sectorNumber)"
.br
.ti -1c
.RI "int \fBByteToSector\fP (int offset)"
.br
.ti -1c
.RI "int \fBFileLength\fP ()"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file filehdr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
