.TH "filehdr" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filehdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBf_magic\fP"
.br
.ti -1c
.RI "unsigned short \fBf_nscns\fP"
.br
.ti -1c
.RI "long \fBf_timdat\fP"
.br
.ti -1c
.RI "long \fBf_symptr\fP"
.br
.ti -1c
.RI "long \fBf_nsyms\fP"
.br
.ti -1c
.RI "unsigned short \fBf_opthdr\fP"
.br
.ti -1c
.RI "unsigned short \fBf_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file coff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
