.TH "Instruction" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Instruction \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDecode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBvalue\fP"
.br
.ti -1c
.RI "unsigned char \fBopCode\fP"
.br
.ti -1c
.RI "unsigned char \fBrs\fP"
.br
.ti -1c
.RI "unsigned char \fBrt\fP"
.br
.ti -1c
.RI "unsigned char \fBrd\fP"
.br
.ti -1c
.RI "int \fBextra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file machine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
