.TH "code/bin/instr.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/instr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBrd\fP(\fBi\fP)   (((\fBi\fP) >> 11) & 0x1f)"
.br
.ti -1c
.RI "#define \fBrt\fP(\fBi\fP)   (((\fBi\fP) >> 16) & 0x1f)"
.br
.ti -1c
.RI "#define \fBrs\fP(\fBi\fP)   (((\fBi\fP) >> 21) & 0x1f)"
.br
.ti -1c
.RI "#define \fBshamt\fP(\fBi\fP)   (((\fBi\fP) >> 6) & 0x1f)"
.br
.ti -1c
.RI "#define \fBimmed\fP(\fBi\fP)   (((\fBi\fP) & 0x8000) ? (i)|(\-0x8000) : (i)&0x7fff)"
.br
.ti -1c
.RI "#define \fBoff26\fP(\fBi\fP)   (((\fBi\fP)&((1<<26)\-1))<<2)"
.br
.ti -1c
.RI "#define \fBtop4\fP(\fBi\fP)   (((\fBi\fP)&(~((1<<28)\-1))))"
.br
.ti -1c
.RI "#define \fBoff16\fP(\fBi\fP)   (\fBimmed\fP(\fBi\fP)<<2)"
.br
.ti -1c
.RI "#define \fBextend\fP(\fBi\fP,  hibitmask)   (((\fBi\fP)&(hibitmask)) ? ((\fBi\fP)|(\-(hibitmask))) : (\fBi\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define extend(\fBi\fP, hibitmask)   (((\fBi\fP)&(hibitmask)) ? ((\fBi\fP)|(\-(hibitmask))) : (\fBi\fP))"

.PP
Definition at line 21 of file instr\&.h\&.
.SS "#define immed(\fBi\fP)   (((\fBi\fP) & 0x8000) ? (i)|(\-0x8000) : (i)&0x7fff)"

.PP
Definition at line 15 of file instr\&.h\&.
.SS "#define off16(\fBi\fP)   (\fBimmed\fP(\fBi\fP)<<2)"

.PP
Definition at line 19 of file instr\&.h\&.
.SS "#define off26(\fBi\fP)   (((\fBi\fP)&((1<<26)\-1))<<2)"

.PP
Definition at line 17 of file instr\&.h\&.
.SS "#define rd(\fBi\fP)   (((\fBi\fP) >> 11) & 0x1f)"

.PP
Definition at line 11 of file instr\&.h\&.
.SS "#define rs(\fBi\fP)   (((\fBi\fP) >> 21) & 0x1f)"

.PP
Definition at line 13 of file instr\&.h\&.
.SS "#define rt(\fBi\fP)   (((\fBi\fP) >> 16) & 0x1f)"

.PP
Definition at line 12 of file instr\&.h\&.
.SS "#define shamt(\fBi\fP)   (((\fBi\fP) >> 6) & 0x1f)"

.PP
Definition at line 14 of file instr\&.h\&.
.SS "#define top4(\fBi\fP)   (((\fBi\fP)&(~((1<<28)\-1))))"

.PP
Definition at line 18 of file instr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
