.TH "code/machine/interrupt.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/interrupt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'list\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPendingInterrupt\fP"
.br
.ti -1c
.RI "class \fBInterrupt\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIntStatus\fP { \fBIntOff\fP, \fBIntOn\fP }"
.br
.ti -1c
.RI "enum \fBMachineStatus\fP { \fBIdleMode\fP, \fBSystemMode\fP, \fBUserMode\fP }"
.br
.ti -1c
.RI "enum \fBIntType\fP { \fBTimerInt\fP, \fBDiskInt\fP, \fBConsoleWriteInt\fP, \fBConsoleReadInt\fP, \fBNetworkSendInt\fP, \fBNetworkRecvInt\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBIntStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIntOff \fP\fP
.TP
\fB\fIIntOn \fP\fP
.PP
Definition at line 42 of file interrupt\&.h\&.
.SS "enum \fBIntType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITimerInt \fP\fP
.TP
\fB\fIDiskInt \fP\fP
.TP
\fB\fIConsoleWriteInt \fP\fP
.TP
\fB\fIConsoleReadInt \fP\fP
.TP
\fB\fINetworkSendInt \fP\fP
.TP
\fB\fINetworkRecvInt \fP\fP
.PP
Definition at line 52 of file interrupt\&.h\&.
.SS "enum \fBMachineStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIdleMode \fP\fP
.TP
\fB\fISystemMode \fP\fP
.TP
\fB\fIUserMode \fP\fP
.PP
Definition at line 47 of file interrupt\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
