.TH "ListElement" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListElement \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListElement\fP (void *itemPtr, long long sortKey)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBListElement\fP * \fBnext\fP"
.br
.ti -1c
.RI "long long \fBkey\fP"
.br
.ti -1c
.RI "void * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
