.TH "Machine" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMachine\fP (bool debug)"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "int \fBReadRegister\fP (int num)"
.br
.ti -1c
.RI "void \fBWriteRegister\fP (int num, int value)"
.br
.ti -1c
.RI "void \fBOneInstruction\fP (\fBInstruction\fP *instr)"
.br
.ti -1c
.RI "void \fBDelayedLoad\fP (int nextReg, int nextVal)"
.br
.ti -1c
.RI "bool \fBReadMem\fP (int addr, int size, int *value)"
.br
.ti -1c
.RI "bool \fBWriteMem\fP (int addr, int size, int value)"
.br
.ti -1c
.RI "ExceptionType \fBTranslate\fP (int virtAddr, int *physAddr, int size, bool writing)"
.br
.ti -1c
.RI "void \fBRaiseException\fP (ExceptionType which, int badVAddr)"
.br
.ti -1c
.RI "void \fBDebugger\fP ()"
.br
.ti -1c
.RI "void \fBDumpState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBmainMemory\fP"
.br
.ti -1c
.RI "int \fBregisters\fP [NumTotalRegs]"
.br
.ti -1c
.RI "\fBTranslationEntry\fP * \fBtlb\fP"
.br
.ti -1c
.RI "\fBTranslationEntry\fP * \fBpageTable\fP"
.br
.ti -1c
.RI "unsigned int \fBpageTableSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file machine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
