.TH "Mail" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mail \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMail\fP (\fBPacketHeader\fP pktH, \fBMailHeader\fP mailH, char *msgData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPacketHeader\fP \fBpktHdr\fP"
.br
.ti -1c
.RI "\fBMailHeader\fP \fBmailHdr\fP"
.br
.ti -1c
.RI "char \fBdata\fP [MaxMailSize]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file post\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
