.TH "code/threads/main.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/threads/main.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThreadTest\fP (void)"
.br
.ti -1c
.RI "void \fBCopy\fP (const char *unixFile, const char *nachosFile)"
.br
.ti -1c
.RI "void \fBPrint\fP (char *file)"
.br
.ti -1c
.RI "void \fBPerformanceTest\fP (void)"
.br
.ti -1c
.RI "void \fBStartProcess\fP (char *file)"
.br
.ti -1c
.RI "void \fBConsoleTest\fP (char *in, char *out)"
.br
.ti -1c
.RI "void \fBSynchConsoleTest\fP (char *in, char *out)"
.br
.ti -1c
.RI "void \fBMailTest\fP (int networkID)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAIN"

.PP
Definition at line 50 of file main\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "void ConsoleTest (char * in, char * out)"

.SS "void Copy (const char * unixFile, const char * nachosFile)"

.PP
Definition at line 32 of file fstest\&.cc\&.
.SS "void MailTest (int networkID)"

.PP
Definition at line 34 of file nettest\&.cc\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 80 of file main\&.cc\&.
.SS "void PerformanceTest (void)"

.PP
Definition at line 173 of file fstest\&.cc\&.
.SS "void Print (char * file)"

.SS "void StartProcess (char * file)"

.SS "void SynchConsoleTest (char * in, char * out)"

.PP
Definition at line 104 of file progtest\&.cc\&.
.SS "void ThreadTest (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
