.TH "code/machine/mipssim.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/mipssim.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOpInfo\fP"
.br
.ti -1c
.RI "struct \fBOpString\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOP_ADD\fP   1"
.br
.ti -1c
.RI "#define \fBOP_ADDI\fP   2"
.br
.ti -1c
.RI "#define \fBOP_ADDIU\fP   3"
.br
.ti -1c
.RI "#define \fBOP_ADDU\fP   4"
.br
.ti -1c
.RI "#define \fBOP_AND\fP   5"
.br
.ti -1c
.RI "#define \fBOP_ANDI\fP   6"
.br
.ti -1c
.RI "#define \fBOP_BEQ\fP   7"
.br
.ti -1c
.RI "#define \fBOP_BGEZ\fP   8"
.br
.ti -1c
.RI "#define \fBOP_BGEZAL\fP   9"
.br
.ti -1c
.RI "#define \fBOP_BGTZ\fP   10"
.br
.ti -1c
.RI "#define \fBOP_BLEZ\fP   11"
.br
.ti -1c
.RI "#define \fBOP_BLTZ\fP   12"
.br
.ti -1c
.RI "#define \fBOP_BLTZAL\fP   13"
.br
.ti -1c
.RI "#define \fBOP_BNE\fP   14"
.br
.ti -1c
.RI "#define \fBOP_DIV\fP   16"
.br
.ti -1c
.RI "#define \fBOP_DIVU\fP   17"
.br
.ti -1c
.RI "#define \fBOP_J\fP   18"
.br
.ti -1c
.RI "#define \fBOP_JAL\fP   19"
.br
.ti -1c
.RI "#define \fBOP_JALR\fP   20"
.br
.ti -1c
.RI "#define \fBOP_JR\fP   21"
.br
.ti -1c
.RI "#define \fBOP_LB\fP   22"
.br
.ti -1c
.RI "#define \fBOP_LBU\fP   23"
.br
.ti -1c
.RI "#define \fBOP_LH\fP   24"
.br
.ti -1c
.RI "#define \fBOP_LHU\fP   25"
.br
.ti -1c
.RI "#define \fBOP_LUI\fP   26"
.br
.ti -1c
.RI "#define \fBOP_LW\fP   27"
.br
.ti -1c
.RI "#define \fBOP_LWL\fP   28"
.br
.ti -1c
.RI "#define \fBOP_LWR\fP   29"
.br
.ti -1c
.RI "#define \fBOP_MFHI\fP   31"
.br
.ti -1c
.RI "#define \fBOP_MFLO\fP   32"
.br
.ti -1c
.RI "#define \fBOP_MTHI\fP   34"
.br
.ti -1c
.RI "#define \fBOP_MTLO\fP   35"
.br
.ti -1c
.RI "#define \fBOP_MULT\fP   36"
.br
.ti -1c
.RI "#define \fBOP_MULTU\fP   37"
.br
.ti -1c
.RI "#define \fBOP_NOR\fP   38"
.br
.ti -1c
.RI "#define \fBOP_OR\fP   39"
.br
.ti -1c
.RI "#define \fBOP_ORI\fP   40"
.br
.ti -1c
.RI "#define \fBOP_RFE\fP   41"
.br
.ti -1c
.RI "#define \fBOP_SB\fP   42"
.br
.ti -1c
.RI "#define \fBOP_SH\fP   43"
.br
.ti -1c
.RI "#define \fBOP_SLL\fP   44"
.br
.ti -1c
.RI "#define \fBOP_SLLV\fP   45"
.br
.ti -1c
.RI "#define \fBOP_SLT\fP   46"
.br
.ti -1c
.RI "#define \fBOP_SLTI\fP   47"
.br
.ti -1c
.RI "#define \fBOP_SLTIU\fP   48"
.br
.ti -1c
.RI "#define \fBOP_SLTU\fP   49"
.br
.ti -1c
.RI "#define \fBOP_SRA\fP   50"
.br
.ti -1c
.RI "#define \fBOP_SRAV\fP   51"
.br
.ti -1c
.RI "#define \fBOP_SRL\fP   52"
.br
.ti -1c
.RI "#define \fBOP_SRLV\fP   53"
.br
.ti -1c
.RI "#define \fBOP_SUB\fP   54"
.br
.ti -1c
.RI "#define \fBOP_SUBU\fP   55"
.br
.ti -1c
.RI "#define \fBOP_SW\fP   56"
.br
.ti -1c
.RI "#define \fBOP_SWL\fP   57"
.br
.ti -1c
.RI "#define \fBOP_SWR\fP   58"
.br
.ti -1c
.RI "#define \fBOP_XOR\fP   59"
.br
.ti -1c
.RI "#define \fBOP_XORI\fP   60"
.br
.ti -1c
.RI "#define \fBOP_SYSCALL\fP   61"
.br
.ti -1c
.RI "#define \fBOP_UNIMP\fP   62"
.br
.ti -1c
.RI "#define \fBOP_RES\fP   63"
.br
.ti -1c
.RI "#define \fBMaxOpcode\fP   63"
.br
.ti -1c
.RI "#define \fBIndexToAddr\fP(x)   ((x) << 2)"
.br
.ti -1c
.RI "#define \fBSIGN_BIT\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBR31\fP   31"
.br
.ti -1c
.RI "#define \fBSPECIAL\fP   100"
.br
.ti -1c
.RI "#define \fBBCOND\fP   101"
.br
.ti -1c
.RI "#define \fBIFMT\fP   1"
.br
.ti -1c
.RI "#define \fBJFMT\fP   2"
.br
.ti -1c
.RI "#define \fBRFMT\fP   3"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRegType\fP { \fBNONE\fP, \fBRS\fP, \fBRT\fP, \fBRD\fP, \fBEXTRA\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BCOND   101"

.PP
Definition at line 106 of file mipssim\&.h\&.
.SS "#define IFMT   1"

.PP
Definition at line 108 of file mipssim\&.h\&.
.SS "#define IndexToAddr(x)   ((x) << 2)"

.PP
Definition at line 94 of file mipssim\&.h\&.
.SS "#define JFMT   2"

.PP
Definition at line 109 of file mipssim\&.h\&.
.SS "#define MaxOpcode   63"

.PP
Definition at line 88 of file mipssim\&.h\&.
.SS "#define OP_ADD   1"

.PP
Definition at line 25 of file mipssim\&.h\&.
.SS "#define OP_ADDI   2"

.PP
Definition at line 26 of file mipssim\&.h\&.
.SS "#define OP_ADDIU   3"

.PP
Definition at line 27 of file mipssim\&.h\&.
.SS "#define OP_ADDU   4"

.PP
Definition at line 28 of file mipssim\&.h\&.
.SS "#define OP_AND   5"

.PP
Definition at line 29 of file mipssim\&.h\&.
.SS "#define OP_ANDI   6"

.PP
Definition at line 30 of file mipssim\&.h\&.
.SS "#define OP_BEQ   7"

.PP
Definition at line 31 of file mipssim\&.h\&.
.SS "#define OP_BGEZ   8"

.PP
Definition at line 32 of file mipssim\&.h\&.
.SS "#define OP_BGEZAL   9"

.PP
Definition at line 33 of file mipssim\&.h\&.
.SS "#define OP_BGTZ   10"

.PP
Definition at line 34 of file mipssim\&.h\&.
.SS "#define OP_BLEZ   11"

.PP
Definition at line 35 of file mipssim\&.h\&.
.SS "#define OP_BLTZ   12"

.PP
Definition at line 36 of file mipssim\&.h\&.
.SS "#define OP_BLTZAL   13"

.PP
Definition at line 37 of file mipssim\&.h\&.
.SS "#define OP_BNE   14"

.PP
Definition at line 38 of file mipssim\&.h\&.
.SS "#define OP_DIV   16"

.PP
Definition at line 40 of file mipssim\&.h\&.
.SS "#define OP_DIVU   17"

.PP
Definition at line 41 of file mipssim\&.h\&.
.SS "#define OP_J   18"

.PP
Definition at line 42 of file mipssim\&.h\&.
.SS "#define OP_JAL   19"

.PP
Definition at line 43 of file mipssim\&.h\&.
.SS "#define OP_JALR   20"

.PP
Definition at line 44 of file mipssim\&.h\&.
.SS "#define OP_JR   21"

.PP
Definition at line 45 of file mipssim\&.h\&.
.SS "#define OP_LB   22"

.PP
Definition at line 46 of file mipssim\&.h\&.
.SS "#define OP_LBU   23"

.PP
Definition at line 47 of file mipssim\&.h\&.
.SS "#define OP_LH   24"

.PP
Definition at line 48 of file mipssim\&.h\&.
.SS "#define OP_LHU   25"

.PP
Definition at line 49 of file mipssim\&.h\&.
.SS "#define OP_LUI   26"

.PP
Definition at line 50 of file mipssim\&.h\&.
.SS "#define OP_LW   27"

.PP
Definition at line 51 of file mipssim\&.h\&.
.SS "#define OP_LWL   28"

.PP
Definition at line 52 of file mipssim\&.h\&.
.SS "#define OP_LWR   29"

.PP
Definition at line 53 of file mipssim\&.h\&.
.SS "#define OP_MFHI   31"

.PP
Definition at line 55 of file mipssim\&.h\&.
.SS "#define OP_MFLO   32"

.PP
Definition at line 56 of file mipssim\&.h\&.
.SS "#define OP_MTHI   34"

.PP
Definition at line 58 of file mipssim\&.h\&.
.SS "#define OP_MTLO   35"

.PP
Definition at line 59 of file mipssim\&.h\&.
.SS "#define OP_MULT   36"

.PP
Definition at line 60 of file mipssim\&.h\&.
.SS "#define OP_MULTU   37"

.PP
Definition at line 61 of file mipssim\&.h\&.
.SS "#define OP_NOR   38"

.PP
Definition at line 62 of file mipssim\&.h\&.
.SS "#define OP_OR   39"

.PP
Definition at line 63 of file mipssim\&.h\&.
.SS "#define OP_ORI   40"

.PP
Definition at line 64 of file mipssim\&.h\&.
.SS "#define OP_RES   63"

.PP
Definition at line 87 of file mipssim\&.h\&.
.SS "#define OP_RFE   41"

.PP
Definition at line 65 of file mipssim\&.h\&.
.SS "#define OP_SB   42"

.PP
Definition at line 66 of file mipssim\&.h\&.
.SS "#define OP_SH   43"

.PP
Definition at line 67 of file mipssim\&.h\&.
.SS "#define OP_SLL   44"

.PP
Definition at line 68 of file mipssim\&.h\&.
.SS "#define OP_SLLV   45"

.PP
Definition at line 69 of file mipssim\&.h\&.
.SS "#define OP_SLT   46"

.PP
Definition at line 70 of file mipssim\&.h\&.
.SS "#define OP_SLTI   47"

.PP
Definition at line 71 of file mipssim\&.h\&.
.SS "#define OP_SLTIU   48"

.PP
Definition at line 72 of file mipssim\&.h\&.
.SS "#define OP_SLTU   49"

.PP
Definition at line 73 of file mipssim\&.h\&.
.SS "#define OP_SRA   50"

.PP
Definition at line 74 of file mipssim\&.h\&.
.SS "#define OP_SRAV   51"

.PP
Definition at line 75 of file mipssim\&.h\&.
.SS "#define OP_SRL   52"

.PP
Definition at line 76 of file mipssim\&.h\&.
.SS "#define OP_SRLV   53"

.PP
Definition at line 77 of file mipssim\&.h\&.
.SS "#define OP_SUB   54"

.PP
Definition at line 78 of file mipssim\&.h\&.
.SS "#define OP_SUBU   55"

.PP
Definition at line 79 of file mipssim\&.h\&.
.SS "#define OP_SW   56"

.PP
Definition at line 80 of file mipssim\&.h\&.
.SS "#define OP_SWL   57"

.PP
Definition at line 81 of file mipssim\&.h\&.
.SS "#define OP_SWR   58"

.PP
Definition at line 82 of file mipssim\&.h\&.
.SS "#define OP_SYSCALL   61"

.PP
Definition at line 85 of file mipssim\&.h\&.
.SS "#define OP_UNIMP   62"

.PP
Definition at line 86 of file mipssim\&.h\&.
.SS "#define OP_XOR   59"

.PP
Definition at line 83 of file mipssim\&.h\&.
.SS "#define OP_XORI   60"

.PP
Definition at line 84 of file mipssim\&.h\&.
.SS "#define R31   31"

.PP
Definition at line 97 of file mipssim\&.h\&.
.SS "#define RFMT   3"

.PP
Definition at line 110 of file mipssim\&.h\&.
.SS "#define SIGN_BIT   0x80000000"

.PP
Definition at line 96 of file mipssim\&.h\&.
.SS "#define SPECIAL   100"

.PP
Definition at line 105 of file mipssim\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRegType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIRS \fP\fP
.TP
\fB\fIRT \fP\fP
.TP
\fB\fIRD \fP\fP
.TP
\fB\fIEXTRA \fP\fP
.PP
Definition at line 155 of file mipssim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
