.TH "code/machine/mipssim.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/mipssim.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'machine\&.h'\fP
.br
\fC#include 'mipssim\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
