.TH "Network" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetwork\fP (NetworkAddress addr, double reliability, VoidFunctionPtr readAvail, VoidFunctionPtr writeDone, int callArg)"
.br
.ti -1c
.RI "void \fBSend\fP (\fBPacketHeader\fP hdr, char *data)"
.br
.ti -1c
.RI "\fBPacketHeader\fP \fBReceive\fP (char *data)"
.br
.ti -1c
.RI "void \fBSendDone\fP ()"
.br
.ti -1c
.RI "void \fBCheckPktAvail\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
