.TH "code/bin/noff.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/bin/noff.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsegment\fP"
.br
.ti -1c
.RI "struct \fBnoffHeader\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNOFFMAGIC\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsegment\fP \fBSegment\fP"
.br
.ti -1c
.RI "typedef struct \fBnoffHeader\fP \fBNoffHeader\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOFFMAGIC"
\fBValue:\fP
.PP
.nf
0xbadfad    /* magic number denoting Nachos 
                     * object code file 
                     */
.fi
.PP
Definition at line 8 of file noff\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBnoffHeader\fP  \fBNoffHeader\fP"

.SS "typedef struct \fBsegment\fP  \fBSegment\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
