.TH "noffHeader" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
noffHeader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnoffMagic\fP"
.br
.ti -1c
.RI "\fBSegment\fP \fBcode\fP"
.br
.ti -1c
.RI "\fBSegment\fP \fBinitData\fP"
.br
.ti -1c
.RI "\fBSegment\fP \fBuninitData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file noff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
