.TH "OpenFile" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenFile\fP (int sector)"
.br
.ti -1c
.RI "void \fBSeek\fP (int position)"
.br
.ti -1c
.RI "int \fBRead\fP (char *into, int numBytes)"
.br
.ti -1c
.RI "int \fBWrite\fP (const char *from, int numBytes)"
.br
.ti -1c
.RI "int \fBReadAt\fP (char *into, int numBytes, int position)"
.br
.ti -1c
.RI "int \fBWriteAt\fP (const char *from, int numBytes, int position)"
.br
.ti -1c
.RI "int \fBLength\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file openfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
