.TH "OpString" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpString \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBstring\fP"
.br
.ti -1c
.RI "RegType \fBargs\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 157 of file mipssim\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
