.TH "PendingInterrupt" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PendingInterrupt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPendingInterrupt\fP (VoidFunctionPtr func, int param, long long time, IntType kind)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VoidFunctionPtr \fBhandler\fP"
.br
.ti -1c
.RI "int \fBarg\fP"
.br
.ti -1c
.RI "long long \fBwhen\fP"
.br
.ti -1c
.RI "IntType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file interrupt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
