.TH "code/network/post.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/network/post.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'network\&.h'\fP
.br
\fC#include 'synchlist\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMailHeader\fP"
.br
.ti -1c
.RI "class \fBMail\fP"
.br
.ti -1c
.RI "class \fBMailBox\fP"
.br
.ti -1c
.RI "class \fBPostOffice\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMaxMailSize\fP   (\fBMaxPacketSize\fP \- sizeof(\fBMailHeader\fP))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBMailBoxAddress\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MaxMailSize   (\fBMaxPacketSize\fP \- sizeof(\fBMailHeader\fP))"

.PP
Definition at line 53 of file post\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBMailBoxAddress\fP"

.PP
Definition at line 36 of file post\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
