.TH "code/test/putchar.c" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/test/putchar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'syscall\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint\fP (char c, int n)"
.br
.ti -1c
.RI "void \fBinterract\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void interract ()"

.PP
Definition at line 11 of file putchar\&.c\&.
.SS "int main ()"

.PP
Definition at line 17 of file putchar\&.c\&.
.SS "void print (char c, int n)"

.PP
Definition at line 3 of file putchar\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
