.TH "Scheduler" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scheduler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReadyToRun\fP (\fBThread\fP *thread)"
.br
.ti -1c
.RI "\fBThread\fP * \fBFindNextToRun\fP ()"
.br
.ti -1c
.RI "void \fBRun\fP (\fBThread\fP *nextThread)"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file scheduler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
