.TH "scnhdr" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scnhdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBs_name\fP [8]"
.br
.ti -1c
.RI "long \fBs_paddr\fP"
.br
.ti -1c
.RI "long \fBs_vaddr\fP"
.br
.ti -1c
.RI "long \fBs_size\fP"
.br
.ti -1c
.RI "long \fBs_scnptr\fP"
.br
.ti -1c
.RI "long \fBs_relptr\fP"
.br
.ti -1c
.RI "long \fBs_lnnoptr\fP"
.br
.ti -1c
.RI "unsigned short \fBs_nreloc\fP"
.br
.ti -1c
.RI "unsigned short \fBs_nlnno\fP"
.br
.ti -1c
.RI "long \fBs_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file coff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
