.TH "Semaphore" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemaphore\fP (const char *debugName, int initialValue)"
.br
.ti -1c
.RI "const char * \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBP\fP ()"
.br
.ti -1c
.RI "void \fBV\fP ()"
.br
.ti -1c
.RI "int \fBE\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file synch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
