.TH "Statistics" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long long \fBtotalTicks\fP"
.br
.ti -1c
.RI "long long \fBidleTicks\fP"
.br
.ti -1c
.RI "long long \fBsystemTicks\fP"
.br
.ti -1c
.RI "long long \fBuserTicks\fP"
.br
.ti -1c
.RI "int \fBnumDiskReads\fP"
.br
.ti -1c
.RI "int \fBnumDiskWrites\fP"
.br
.ti -1c
.RI "int \fBnumConsoleCharsRead\fP"
.br
.ti -1c
.RI "int \fBnumConsoleCharsWritten\fP"
.br
.ti -1c
.RI "int \fBnumPageFaults\fP"
.br
.ti -1c
.RI "int \fBnumPacketsSent\fP"
.br
.ti -1c
.RI "int \fBnumPacketsRecvd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file stats\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
