.TH "code/machine/stats.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/stats.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatistics\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUserTick\fP   1"
.br
.ti -1c
.RI "#define \fBSystemTick\fP   10"
.br
.ti -1c
.RI "#define \fBRotationTime\fP   500"
.br
.ti -1c
.RI "#define \fBSeekTime\fP   500"
.br
.ti -1c
.RI "#define \fBConsoleTime\fP   100"
.br
.ti -1c
.RI "#define \fBNetworkTime\fP   100"
.br
.ti -1c
.RI "#define \fBTimerTicks\fP   100"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ConsoleTime   100"

.PP
Definition at line 66 of file stats\&.h\&.
.SS "#define NetworkTime   100"

.PP
Definition at line 67 of file stats\&.h\&.
.SS "#define RotationTime   500"

.PP
Definition at line 64 of file stats\&.h\&.
.SS "#define SeekTime   500"

.PP
Definition at line 65 of file stats\&.h\&.
.SS "#define SystemTick   10"

.PP
Definition at line 63 of file stats\&.h\&.
.SS "#define TimerTicks   100"

.PP
Definition at line 68 of file stats\&.h\&.
.SS "#define UserTick   1"

.PP
Definition at line 62 of file stats\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
