.TH "code/userprog/stringtransfer.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/userprog/stringtransfer.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'system\&.h'\fP
.br
\fC#include 'machine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcopyStringFromMachine\fP (int from, unsigned int max_size)"
.br
.ti -1c
.RI "void \fBcopyStringToMachine\fP (char *\fBstring\fP, int to, unsigned max_size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* copyStringFromMachine (int from, unsigned int max_size)"

.PP
Definition at line 5 of file stringtransfer\&.cc\&.
.SS "void copyStringToMachine (char * string, int to, unsigned max_size)"

.PP
Definition at line 22 of file stringtransfer\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
