.TH "code/threads/synch.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/threads/synch.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'thread\&.h'\fP
.br
\fC#include 'list\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSemaphore\fP"
.br
.ti -1c
.RI "class \fBLock\fP"
.br
.ti -1c
.RI "class \fBCondition\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
