.TH "SynchList" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SynchList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAppend\fP (void *item)"
.br
.ti -1c
.RI "void * \fBRemove\fP ()"
.br
.ti -1c
.RI "void \fBMapcar\fP (VoidFunctionPtr func)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file synchlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
