.TH "code/userprog/syscall.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/userprog/syscall.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC_Halt\fP   0"
.br
.ti -1c
.RI "#define \fBSC_Exit\fP   1"
.br
.ti -1c
.RI "#define \fBSC_Exec\fP   2"
.br
.ti -1c
.RI "#define \fBSC_Join\fP   3"
.br
.ti -1c
.RI "#define \fBSC_Create\fP   4"
.br
.ti -1c
.RI "#define \fBSC_Open\fP   5"
.br
.ti -1c
.RI "#define \fBSC_Read\fP   6"
.br
.ti -1c
.RI "#define \fBSC_Write\fP   7"
.br
.ti -1c
.RI "#define \fBSC_Close\fP   8"
.br
.ti -1c
.RI "#define \fBSC_Fork\fP   9"
.br
.ti -1c
.RI "#define \fBSC_Yield\fP   10"
.br
.ti -1c
.RI "#define \fBSC_PutChar\fP   11"
.br
.ti -1c
.RI "#define \fBSC_GetChar\fP   12"
.br
.ti -1c
.RI "#define \fBSC_PutString\fP   13"
.br
.ti -1c
.RI "#define \fBSC_GetString\fP   14"
.br
.ti -1c
.RI "#define \fBSC_PutInt\fP   15"
.br
.ti -1c
.RI "#define \fBSC_GetInt\fP   16"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SC_Close   8"

.PP
Definition at line 29 of file syscall\&.h\&.
.SS "#define SC_Create   4"

.PP
Definition at line 25 of file syscall\&.h\&.
.SS "#define SC_Exec   2"

.PP
Definition at line 23 of file syscall\&.h\&.
.SS "#define SC_Exit   1"

.PP
Definition at line 22 of file syscall\&.h\&.
.SS "#define SC_Fork   9"

.PP
Definition at line 30 of file syscall\&.h\&.
.SS "#define SC_GetChar   12"

.PP
Definition at line 33 of file syscall\&.h\&.
.SS "#define SC_GetInt   16"

.PP
Definition at line 37 of file syscall\&.h\&.
.SS "#define SC_GetString   14"

.PP
Definition at line 35 of file syscall\&.h\&.
.SS "#define SC_Halt   0"

.PP
Definition at line 21 of file syscall\&.h\&.
.SS "#define SC_Join   3"

.PP
Definition at line 24 of file syscall\&.h\&.
.SS "#define SC_Open   5"

.PP
Definition at line 26 of file syscall\&.h\&.
.SS "#define SC_PutChar   11"

.PP
Definition at line 32 of file syscall\&.h\&.
.SS "#define SC_PutInt   15"

.PP
Definition at line 36 of file syscall\&.h\&.
.SS "#define SC_PutString   13"

.PP
Definition at line 34 of file syscall\&.h\&.
.SS "#define SC_Read   6"

.PP
Definition at line 27 of file syscall\&.h\&.
.SS "#define SC_Write   7"

.PP
Definition at line 28 of file syscall\&.h\&.
.SS "#define SC_Yield   10"

.PP
Definition at line 31 of file syscall\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
