.TH "code/machine/sysdep.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/sysdep.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBPollFile\fP (int fd)"
.br
.ti -1c
.RI "int \fBOpenForWrite\fP (const char *name)"
.br
.ti -1c
.RI "int \fBOpenForReadWrite\fP (const char *name, bool crashOnError)"
.br
.ti -1c
.RI "void \fBRead\fP (int fd, char *buffer, int nBytes)"
.br
.ti -1c
.RI "int \fBReadPartial\fP (int fd, char *buffer, int nBytes)"
.br
.ti -1c
.RI "void \fBWriteFile\fP (int fd, const char *buffer, int nBytes)"
.br
.ti -1c
.RI "void \fBLseek\fP (int fd, int offset, int whence)"
.br
.ti -1c
.RI "int \fBTell\fP (int fd)"
.br
.ti -1c
.RI "void \fBClose\fP (int fd)"
.br
.ti -1c
.RI "bool \fBUnlink\fP (const char *name)"
.br
.ti -1c
.RI "int \fBOpenSocket\fP ()"
.br
.ti -1c
.RI "void \fBCloseSocket\fP (int sockID)"
.br
.ti -1c
.RI "void \fBAssignNameToSocket\fP (const char *socketName, int sockID)"
.br
.ti -1c
.RI "void \fBDeAssignNameToSocket\fP (const char *socketName)"
.br
.ti -1c
.RI "bool \fBPollSocket\fP (int sockID)"
.br
.ti -1c
.RI "void \fBReadFromSocket\fP (int sockID, char *buffer, int packetSize)"
.br
.ti -1c
.RI "void \fBSendToSocket\fP (int sockID, const char *buffer, int packetSize, const char *toName)"
.br
.ti -1c
.RI "void \fBAbort\fP ()"
.br
.ti -1c
.RI "void \fBExit\fP (int exitCode)"
.br
.ti -1c
.RI "void \fBDelay\fP (int seconds)"
.br
.ti -1c
.RI "void \fBCallOnUserAbort\fP (\fBVoidNoArgFunctionPtr\fP cleanUp)"
.br
.ti -1c
.RI "void \fBRandomInit\fP (unsigned seed)"
.br
.ti -1c
.RI "int \fBRandom\fP ()"
.br
.ti -1c
.RI "char * \fBAllocBoundedArray\fP (int size)"
.br
.ti -1c
.RI "void \fBDeallocBoundedArray\fP (char *p, int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Abort ()"

.PP
Definition at line 426 of file sysdep\&.cc\&.
.SS "char* AllocBoundedArray (int size)"

.PP
Definition at line 478 of file sysdep\&.cc\&.
.SS "void AssignNameToSocket (const char * socketName, int sockID)"

.PP
Definition at line 310 of file sysdep\&.cc\&.
.SS "void CallOnUserAbort (\fBVoidNoArgFunctionPtr\fP cleanUp)"

.PP
Definition at line 402 of file sysdep\&.cc\&.
.SS "void Close (int fd)"

.PP
Definition at line 245 of file sysdep\&.cc\&.
.SS "void CloseSocket (int sockID)"

.PP
Definition at line 286 of file sysdep\&.cc\&.
.SS "void DeallocBoundedArray (char * p, int size)"

.PP
Definition at line 497 of file sysdep\&.cc\&.
.SS "void DeAssignNameToSocket (const char * socketName)"

.PP
Definition at line 328 of file sysdep\&.cc\&.
.SS "void Delay (int seconds)"

.PP
Definition at line 415 of file sysdep\&.cc\&.
.SS "void Exit (int exitCode)"

.PP
Definition at line 437 of file sysdep\&.cc\&.
.SS "void Lseek (int fd, int offset, int whence)"

.PP
Definition at line 217 of file sysdep\&.cc\&.
.SS "int OpenForReadWrite (const char * name, bool crashOnError)"

.PP
Definition at line 166 of file sysdep\&.cc\&.
.SS "int OpenForWrite (const char * name)"

.PP
Definition at line 149 of file sysdep\&.cc\&.
.SS "int OpenSocket ()"

.PP
Definition at line 270 of file sysdep\&.cc\&.
.SS "bool PollFile (int fd)"

.PP
Definition at line 115 of file sysdep\&.cc\&.
.SS "bool PollSocket (int sockID)"

.PP
Definition at line 339 of file sysdep\&.cc\&.
.SS "int Random ()"

.PP
Definition at line 460 of file sysdep\&.cc\&.
.SS "void RandomInit (unsigned seed)"

.PP
Definition at line 449 of file sysdep\&.cc\&.
.SS "void Read (int fd, char * buffer, int nBytes)"

.PP
Definition at line 37 of file coff2flat\&.c\&.
.SS "void ReadFromSocket (int sockID, char * buffer, int packetSize)"

.PP
Definition at line 349 of file sysdep\&.cc\&.
.SS "int ReadPartial (int fd, char * buffer, int nBytes)"

.PP
Definition at line 193 of file sysdep\&.cc\&.
.SS "void SendToSocket (int sockID, const char * buffer, int packetSize, const char * toName)"

.PP
Definition at line 383 of file sysdep\&.cc\&.
.SS "int Tell (int fd)"

.PP
Definition at line 229 of file sysdep\&.cc\&.
.SS "bool Unlink (const char * name)"

.PP
Definition at line 257 of file sysdep\&.cc\&.
.SS "void WriteFile (int fd, const char * buffer, int nBytes)"

.PP
Definition at line 205 of file sysdep\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
