.TH "code/threads/system.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/threads/system.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBThread\fP * \fBcurrentThread\fP"
.br
.ti -1c
.RI "\fBThread\fP * \fBthreadToBeDestroyed\fP"
.br
.ti -1c
.RI "\fBScheduler\fP * \fBscheduler\fP"
.br
.ti -1c
.RI "\fBInterrupt\fP * \fBinterrupt\fP"
.br
.ti -1c
.RI "\fBStatistics\fP * \fBstats\fP"
.br
.ti -1c
.RI "\fBTimer\fP * \fBtimer\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Cleanup ()"

.PP
Definition at line 182 of file system\&.cc\&.
.SS "void Initialize (int argc, char ** argv)"

.PP
Definition at line 79 of file system\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "\fBThread\fP* currentThread"

.PP
Definition at line 14 of file system\&.cc\&.
.SS "\fBInterrupt\fP* interrupt"

.PP
Definition at line 17 of file system\&.cc\&.
.SS "\fBScheduler\fP* scheduler"

.PP
Definition at line 16 of file system\&.cc\&.
.SS "\fBStatistics\fP* stats"

.PP
Definition at line 18 of file system\&.cc\&.
.SS "\fBThread\fP* threadToBeDestroyed"

.PP
Definition at line 15 of file system\&.cc\&.
.SS "\fBTimer\fP* timer"

.PP
Definition at line 19 of file system\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
