.TH "code/machine/timer.h" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/timer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
