.TH "code/machine/translate.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/machine/translate.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'machine\&.h'\fP
.br
\fC#include 'addrspace\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBWordToHost\fP (unsigned int word)"
.br
.ti -1c
.RI "unsigned short \fBShortToHost\fP (unsigned short shortword)"
.br
.ti -1c
.RI "unsigned int \fBWordToMachine\fP (unsigned int word)"
.br
.ti -1c
.RI "unsigned short \fBShortToMachine\fP (unsigned short shortword)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned short ShortToHost (unsigned short shortword)"

.PP
Definition at line 56 of file translate\&.cc\&.
.SS "unsigned short ShortToMachine (unsigned short shortword)"

.PP
Definition at line 71 of file translate\&.cc\&.
.SS "unsigned int WordToHost (unsigned int word)"

.PP
Definition at line 42 of file translate\&.cc\&.
.SS "unsigned int WordToMachine (unsigned int word)"

.PP
Definition at line 68 of file translate\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
