.TH "TranslationEntry" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslationEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBvirtualPage\fP"
.br
.ti -1c
.RI "unsigned int \fBphysicalPage\fP"
.br
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "bool \fBreadOnly\fP"
.br
.ti -1c
.RI "bool \fBuse\fP"
.br
.ti -1c
.RI "bool \fBdirty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file translate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
