.TH "code/threads/utility.cc" 3 "Tue Dec 19 2017" "Version nachos-teamd" "OS-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/threads/utility.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'copyright\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br
\fC#include '/usr/include/stdarg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDebugInit\fP (const char *flagList)"
.br
.ti -1c
.RI "bool \fBDebugIsEnabled\fP (char flag)"
.br
.ti -1c
.RI "void \fBDEBUG\fP (char flag, const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DEBUG (char flag, const char * format,  \&.\&.\&.)"

.PP
Definition at line 61 of file utility\&.cc\&.
.SS "void DebugInit (const char * flagList)"

.PP
Definition at line 34 of file utility\&.cc\&.
.SS "bool DebugIsEnabled (char flag)"

.PP
Definition at line 45 of file utility\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OS-Project from the source code\&.
